### ISSUE TITLE
通讯中

### ISSUE THREAD

**Issue by mokizzz** [ffobook/ffobook#19]
@zihammmm 还在玩游戏吗~ 本站准备搬迁至 [FFOWiki](http://ffo.gamekee.com/) 了，有没有兴趣来做管理员呀

**Comment by zihammmm** [comment]
做管理员需要做什么

**Comment by mokizzz** [comment]
> 做管理员需要做什么

和这里做的一样，可以贡献内容，可以发布新闻公告，人数多了以后还可以管理社区。（也支持偷懒）
如果有人赞助，有贡献的话还可以分钱😂。
目前在搬内容，如果感兴趣也可以一起搬。
wiki系统相比 ffobook 这种静态网页，可编辑性更强，而且挂靠在wiki农场上也不用自己出服务器和域名费，所以我准备搬过去。
大致如👆

**Comment by zihammmm** [comment]
那可以。我之前还想搬到自己的服务器。

**Comment by mokizzz** [comment]
> 那可以。我之前还想搬到自己的服务器。

那就在 [http://ffo.gamekee.com/](http://ffo.gamekee.com/) 注册登录后申请当管理员吧，申请理由注明是你，我给通过了就可以了。登录建议选QQ微信，我看手机号登录登不上。

**Comment by zihammmm** [comment]
申请了。

**Comment by mokizzz** [comment]
> 申请了。

已同意，稍等一会儿就好了
