### ISSUE TITLE
考虑增加骗子名单

### ISSUE THREAD

**Issue by zihammmm** [ffobook/ffobook#8]
是否可以在贴吧收集骗子ID，将ID收集起来集中在防骗手册中？

**Comment by mokizzz** [comment]
不太现实。
一是骗子ID更换成本低，很难将所有骗子ID都涵盖完全，且后期维护成本大。
二是即使做出来，来此网站查骗子ID也比较麻烦，很少会有人来查。
授人以鱼不如授人以渔，直接教授防骗技巧更有效果。
目前我对自己做的防骗手册还不太满意，大量文字不太容易阅读，准备将其修改为防骗漫画的格式。
